insert into area (area_id, area_name) values (1, 'Elgar');
insert into area (area_id, area_name) values (2, 'Swallow');
insert into area (area_id, area_name) values (3, 'Pond');
insert into area (area_id, area_name) values (4, 'Pawling');
insert into area (area_id, area_name) values (5, 'Amoth');
insert into area (area_id, area_name) values (6, 'Lawn');
insert into area (area_id, area_name) values (7, 'Ruskin');
insert into area (area_id, area_name) values (8, 'Vahlen');
insert into area (area_id, area_name) values (9, 'Burning Wood');
insert into area (area_id, area_name) values (10, 'Moose');
insert into area (area_id, area_name) values (11, 'La Follette');
insert into area (area_id, area_name) values (12, 'Shasta');
insert into area (area_id, area_name) values (13, 'Rowland');
insert into area (area_id, area_name) values (14, 'Doe Crossing');
insert into area (area_id, area_name) values (15, 'Sommers');
insert into area (area_id, area_name) values (16, 'Carey');
insert into area (area_id, area_name) values (17, 'Pearson');
insert into area (area_id, area_name) values (18, 'Sherman');
insert into area (area_id, area_name) values (19, 'Jay');
insert into area (area_id, area_name) values (20, 'Petterle');
insert into area (area_id, area_name) values (21, 'Bunting');
insert into area (area_id, area_name) values (22, 'Esch');
insert into area (area_id, area_name) values (23, '1st');
insert into area (area_id, area_name) values (24, 'Dahle');
insert into area (area_id, area_name) values (25, 'Chive');
insert into area (area_id, area_name) values (26, 'Northridge');
insert into area (area_id, area_name) values (27, 'Doe Crossing');
insert into area (area_id, area_name) values (28, 'Sunbrook');
insert into area (area_id, area_name) values (29, 'Hintze');
insert into area (area_id, area_name) values (30, 'Brown');
insert into area (area_id, area_name) values (31, 'Helena');
insert into area (area_id, area_name) values (32, 'Basil');
insert into area (area_id, area_name) values (33, 'Miller');
insert into area (area_id, area_name) values (34, 'Old Gate');
insert into area (area_id, area_name) values (35, 'Elmside');
insert into area (area_id, area_name) values (36, 'Old Gate');
insert into area (area_id, area_name) values (37, 'Portage');
insert into area (area_id, area_name) values (38, 'Nobel');
insert into area (area_id, area_name) values (39, 'Lillian');
insert into area (area_id, area_name) values (40, 'Rieder');
insert into area (area_id, area_name) values (41, 'Crescent Oaks');
insert into area (area_id, area_name) values (42, 'Dapin');
insert into area (area_id, area_name) values (43, 'Grim');
insert into area (area_id, area_name) values (44, 'Ridgeway');
insert into area (area_id, area_name) values (45, 'Mariners Cove');
insert into area (area_id, area_name) values (46, 'Bowman');
insert into area (area_id, area_name) values (47, 'Transport');
insert into area (area_id, area_name) values (48, 'Oak');
insert into area (area_id, area_name) values (49, 'Springs');
insert into area (area_id, area_name) values (50, 'Loeprich');
insert into area (area_id, area_name) values (51, 'Anderson');
insert into area (area_id, area_name) values (52, 'Sycamore');
insert into area (area_id, area_name) values (53, 'Golf View');
insert into area (area_id, area_name) values (54, 'Orin');
insert into area (area_id, area_name) values (55, 'Corscot');
insert into area (area_id, area_name) values (56, 'Rockefeller');
insert into area (area_id, area_name) values (57, 'Hoard');
insert into area (area_id, area_name) values (58, 'Spohn');
insert into area (area_id, area_name) values (59, 'Coolidge');
insert into area (area_id, area_name) values (60, 'Arrowood');
insert into area (area_id, area_name) values (61, 'Eliot');
insert into area (area_id, area_name) values (62, 'Sunbrook');
insert into area (area_id, area_name) values (63, 'Anniversary');
insert into area (area_id, area_name) values (64, 'Fuller');
insert into area (area_id, area_name) values (65, 'Randy');
insert into area (area_id, area_name) values (66, 'Troy');
insert into area (area_id, area_name) values (67, 'Esch');
insert into area (area_id, area_name) values (68, 'Westport');
insert into area (area_id, area_name) values (69, 'Brown');
insert into area (area_id, area_name) values (70, 'Ruskin');
insert into area (area_id, area_name) values (71, 'Doe Crossing');
insert into area (area_id, area_name) values (72, 'Montana');
insert into area (area_id, area_name) values (73, 'Merry');
insert into area (area_id, area_name) values (74, 'Becker');
insert into area (area_id, area_name) values (75, 'Victoria');
insert into area (area_id, area_name) values (76, 'Sommers');
insert into area (area_id, area_name) values (77, 'Harbort');
insert into area (area_id, area_name) values (78, 'Forest');
insert into area (area_id, area_name) values (79, 'South');
insert into area (area_id, area_name) values (80, 'Sunnyside');
insert into area (area_id, area_name) values (81, 'Lawn');
insert into area (area_id, area_name) values (82, 'Cambridge');
insert into area (area_id, area_name) values (83, 'Fisk');
insert into area (area_id, area_name) values (84, 'Gina');
insert into area (area_id, area_name) values (85, 'Bashford');
insert into area (area_id, area_name) values (86, 'West');
insert into area (area_id, area_name) values (87, 'Nancy');
insert into area (area_id, area_name) values (88, 'Gulseth');
insert into area (area_id, area_name) values (89, 'Petterle');
insert into area (area_id, area_name) values (90, 'Westport');
insert into area (area_id, area_name) values (91, 'Morrow');
insert into area (area_id, area_name) values (92, 'Del Mar');
insert into area (area_id, area_name) values (93, 'Autumn Leaf');
insert into area (area_id, area_name) values (94, 'Cody');
insert into area (area_id, area_name) values (95, 'Sachtjen');
insert into area (area_id, area_name) values (96, 'Alpine');
insert into area (area_id, area_name) values (97, 'Service');
insert into area (area_id, area_name) values (98, 'Judy');
insert into area (area_id, area_name) values (99, 'Portage');
insert into area (area_id, area_name) values (100, 'Pearson');
insert into area (area_id, area_name) values (101, 'Claremont');
insert into area (area_id, area_name) values (102, 'Moose');
insert into area (area_id, area_name) values (103, 'Pine View');
insert into area (area_id, area_name) values (104, 'Clemons');
insert into area (area_id, area_name) values (105, 'Schmedeman');
insert into area (area_id, area_name) values (106, 'Hooker');
insert into area (area_id, area_name) values (107, 'Mosinee');
insert into area (area_id, area_name) values (108, 'Hermina');
insert into area (area_id, area_name) values (109, 'Glendale');
insert into area (area_id, area_name) values (110, 'Sachtjen');
insert into area (area_id, area_name) values (111, 'Petterle');
insert into area (area_id, area_name) values (112, 'Village');
insert into area (area_id, area_name) values (113, 'Kim');
insert into area (area_id, area_name) values (114, 'Cody');
insert into area (area_id, area_name) values (115, 'Green');
insert into area (area_id, area_name) values (116, 'Norway Maple');
insert into area (area_id, area_name) values (117, 'Rusk');
insert into area (area_id, area_name) values (118, 'Iowa');
insert into area (area_id, area_name) values (119, 'Union');
insert into area (area_id, area_name) values (120, 'Dapin');
insert into area (area_id, area_name) values (121, 'Maple');
insert into area (area_id, area_name) values (122, 'Lillian');
insert into area (area_id, area_name) values (123, 'Hooker');
insert into area (area_id, area_name) values (124, 'Lawn');
insert into area (area_id, area_name) values (125, 'Westridge');
insert into area (area_id, area_name) values (126, 'Hoepker');
insert into area (area_id, area_name) values (127, 'Morning');
insert into area (area_id, area_name) values (128, 'Hollow Ridge');
insert into area (area_id, area_name) values (129, 'Nelson');
insert into area (area_id, area_name) values (130, 'Briar Crest');
insert into area (area_id, area_name) values (131, 'Talisman');
insert into area (area_id, area_name) values (132, 'Judy');
insert into area (area_id, area_name) values (133, 'Corscot');
insert into area (area_id, area_name) values (134, 'Westridge');
insert into area (area_id, area_name) values (135, 'Badeau');
insert into area (area_id, area_name) values (136, 'Melby');
insert into area (area_id, area_name) values (137, 'Mesta');
insert into area (area_id, area_name) values (138, 'Lake View');
insert into area (area_id, area_name) values (139, 'Morrow');
insert into area (area_id, area_name) values (140, 'Prentice');
insert into area (area_id, area_name) values (141, 'Pankratz');
insert into area (area_id, area_name) values (142, 'Fairfield');
insert into area (area_id, area_name) values (143, 'Forest Run');
insert into area (area_id, area_name) values (144, 'Ridgeway');
insert into area (area_id, area_name) values (145, 'Dexter');
insert into area (area_id, area_name) values (146, 'Mendota');
insert into area (area_id, area_name) values (147, 'Truax');
insert into area (area_id, area_name) values (148, 'Debs');
insert into area (area_id, area_name) values (149, 'Brown');
insert into area (area_id, area_name) values (150, 'Old Shore');
insert into area (area_id, area_name) values (151, 'Alpine');
insert into area (area_id, area_name) values (152, 'Victoria');
insert into area (area_id, area_name) values (153, 'Briar Crest');
insert into area (area_id, area_name) values (154, 'Blackbird');
insert into area (area_id, area_name) values (155, 'Brentwood');
insert into area (area_id, area_name) values (156, 'Portage');
insert into area (area_id, area_name) values (157, 'Lunder');
insert into area (area_id, area_name) values (158, 'Maple');
insert into area (area_id, area_name) values (159, 'Arkansas');
insert into area (area_id, area_name) values (160, 'Ridgeway');
insert into area (area_id, area_name) values (161, 'Northfield');
insert into area (area_id, area_name) values (162, 'Knutson');
insert into area (area_id, area_name) values (163, 'Scott');
insert into area (area_id, area_name) values (164, 'Spenser');
insert into area (area_id, area_name) values (165, 'Manufacturers');
insert into area (area_id, area_name) values (166, 'High Crossing');
insert into area (area_id, area_name) values (167, 'Reinke');
insert into area (area_id, area_name) values (168, 'Delaware');
insert into area (area_id, area_name) values (169, 'Novick');
insert into area (area_id, area_name) values (170, 'Forest Run');
insert into area (area_id, area_name) values (171, 'Meadow Vale');
insert into area (area_id, area_name) values (172, 'Eastlawn');
insert into area (area_id, area_name) values (173, 'Texas');
insert into area (area_id, area_name) values (174, 'Northview');
insert into area (area_id, area_name) values (175, 'Chive');
insert into area (area_id, area_name) values (176, 'Maple');
insert into area (area_id, area_name) values (177, 'Loftsgordon');
insert into area (area_id, area_name) values (178, 'Melody');
insert into area (area_id, area_name) values (179, 'Maple');
insert into area (area_id, area_name) values (180, 'Superior');
insert into area (area_id, area_name) values (181, 'Pond');
insert into area (area_id, area_name) values (182, 'Delaware');
insert into area (area_id, area_name) values (183, 'Parkside');
insert into area (area_id, area_name) values (184, 'Trailsway');
insert into area (area_id, area_name) values (185, 'Walton');
insert into area (area_id, area_name) values (186, 'Bayside');
insert into area (area_id, area_name) values (187, 'Loomis');
insert into area (area_id, area_name) values (188, 'Elmside');
insert into area (area_id, area_name) values (189, 'Hovde');
insert into area (area_id, area_name) values (190, 'Bowman');
insert into area (area_id, area_name) values (191, 'Prairieview');
insert into area (area_id, area_name) values (192, 'Dayton');
insert into area (area_id, area_name) values (193, 'Delaware');
insert into area (area_id, area_name) values (194, 'Center');
insert into area (area_id, area_name) values (195, 'Linden');
insert into area (area_id, area_name) values (196, 'Leroy');
insert into area (area_id, area_name) values (197, 'Katie');
insert into area (area_id, area_name) values (198, 'Ronald Regan');
insert into area (area_id, area_name) values (199, 'Delaware');
insert into area (area_id, area_name) values (200, 'Muir');
insert into area (area_id, area_name) values (201, 'Bobwhite');
insert into area (area_id, area_name) values (202, 'Superior');
insert into area (area_id, area_name) values (203, 'Havey');
insert into area (area_id, area_name) values (204, 'Melody');
insert into area (area_id, area_name) values (205, 'Fairfield');
insert into area (area_id, area_name) values (206, 'Eliot');
insert into area (area_id, area_name) values (207, 'Sutteridge');
insert into area (area_id, area_name) values (208, 'Corscot');
insert into area (area_id, area_name) values (209, 'Kedzie');
insert into area (area_id, area_name) values (210, 'Crest Line');
insert into area (area_id, area_name) values (211, 'Holmberg');
insert into area (area_id, area_name) values (212, 'Lawn');
insert into area (area_id, area_name) values (213, 'Lighthouse Bay');
insert into area (area_id, area_name) values (214, 'Fairfield');
insert into area (area_id, area_name) values (215, 'Sage');
insert into area (area_id, area_name) values (216, 'Crest Line');
insert into area (area_id, area_name) values (217, 'Bartillon');
insert into area (area_id, area_name) values (218, 'Harbort');
insert into area (area_id, area_name) values (219, 'Pennsylvania');
insert into area (area_id, area_name) values (220, '2nd');
insert into area (area_id, area_name) values (221, 'Holy Cross');
insert into area (area_id, area_name) values (222, 'Ramsey');
insert into area (area_id, area_name) values (223, 'Hoepker');
insert into area (area_id, area_name) values (224, 'Heath');
insert into area (area_id, area_name) values (225, 'Mcbride');
insert into area (area_id, area_name) values (226, 'West');
insert into area (area_id, area_name) values (227, 'Eliot');
insert into area (area_id, area_name) values (228, 'Jackson');
insert into area (area_id, area_name) values (229, 'Sunfield');
insert into area (area_id, area_name) values (230, 'Elka');
insert into area (area_id, area_name) values (231, 'Norway Maple');
insert into area (area_id, area_name) values (232, 'Village');
insert into area (area_id, area_name) values (233, 'Huxley');
insert into area (area_id, area_name) values (234, 'Cottonwood');
insert into area (area_id, area_name) values (235, 'Truax');
insert into area (area_id, area_name) values (236, 'Anzinger');
insert into area (area_id, area_name) values (237, 'Myrtle');
insert into area (area_id, area_name) values (238, 'Coolidge');
insert into area (area_id, area_name) values (239, 'Artisan');
insert into area (area_id, area_name) values (240, 'Vernon');
insert into area (area_id, area_name) values (241, 'Arapahoe');
insert into area (area_id, area_name) values (242, 'Sutherland');
insert into area (area_id, area_name) values (243, 'Monument');
insert into area (area_id, area_name) values (244, 'Bultman');
insert into area (area_id, area_name) values (245, 'Crownhardt');
insert into area (area_id, area_name) values (246, 'Forster');
insert into area (area_id, area_name) values (247, 'Banding');
insert into area (area_id, area_name) values (248, 'American');
insert into area (area_id, area_name) values (249, 'Merry');
insert into area (area_id, area_name) values (250, 'Ryan');
insert into area (area_id, area_name) values (251, 'Fair Oaks');
insert into area (area_id, area_name) values (252, 'Hollow Ridge');
insert into area (area_id, area_name) values (253, 'Northridge');
insert into area (area_id, area_name) values (254, 'Village Green');
insert into area (area_id, area_name) values (255, 'Packers');
insert into area (area_id, area_name) values (256, 'Maywood');
insert into area (area_id, area_name) values (257, 'Coleman');
insert into area (area_id, area_name) values (258, 'Hooker');
insert into area (area_id, area_name) values (259, 'Hansons');
insert into area (area_id, area_name) values (260, 'Rigney');
insert into area (area_id, area_name) values (261, 'Paget');
insert into area (area_id, area_name) values (262, 'Amoth');
insert into area (area_id, area_name) values (263, 'Gulseth');
insert into area (area_id, area_name) values (264, 'Clarendon');
insert into area (area_id, area_name) values (265, 'School');
insert into area (area_id, area_name) values (266, 'Jenna');
insert into area (area_id, area_name) values (267, 'Dwight');
insert into area (area_id, area_name) values (268, 'Harper');
insert into area (area_id, area_name) values (269, '6th');
insert into area (area_id, area_name) values (270, 'Northview');
insert into area (area_id, area_name) values (271, 'Novick');
insert into area (area_id, area_name) values (272, 'Superior');
insert into area (area_id, area_name) values (273, 'Lerdahl');
insert into area (area_id, area_name) values (274, 'Little Fleur');
insert into area (area_id, area_name) values (275, 'Texas');
insert into area (area_id, area_name) values (276, 'Anhalt');
insert into area (area_id, area_name) values (277, 'Oxford');
insert into area (area_id, area_name) values (278, 'Grasskamp');
insert into area (area_id, area_name) values (279, 'Duke');
insert into area (area_id, area_name) values (280, 'Miller');
insert into area (area_id, area_name) values (281, 'Porter');
insert into area (area_id, area_name) values (282, 'Pond');
insert into area (area_id, area_name) values (283, 'Monterey');
insert into area (area_id, area_name) values (284, 'Hollow Ridge');
insert into area (area_id, area_name) values (285, '8th');
insert into area (area_id, area_name) values (286, 'Melody');
insert into area (area_id, area_name) values (287, 'Memorial');
insert into area (area_id, area_name) values (288, 'Kennedy');
insert into area (area_id, area_name) values (289, 'Jackson');
insert into area (area_id, area_name) values (290, 'Warbler');
insert into area (area_id, area_name) values (291, 'Luster');
insert into area (area_id, area_name) values (292, 'West');
insert into area (area_id, area_name) values (293, 'Melody');
insert into area (area_id, area_name) values (294, 'Almo');
insert into area (area_id, area_name) values (295, 'Burning Wood');
insert into area (area_id, area_name) values (296, 'Steensland');
insert into area (area_id, area_name) values (297, 'Shelley');
insert into area (area_id, area_name) values (298, 'Dryden');
insert into area (area_id, area_name) values (299, 'Center');
insert into area (area_id, area_name) values (300, 'Swallow');
insert into area (area_id, area_name) values (301, 'Leroy');
insert into area (area_id, area_name) values (302, 'Cascade');
insert into area (area_id, area_name) values (303, 'Mcbride');
insert into area (area_id, area_name) values (304, 'Fair Oaks');
insert into area (area_id, area_name) values (305, 'Dayton');
insert into area (area_id, area_name) values (306, 'Sycamore');
insert into area (area_id, area_name) values (307, 'Maple');
insert into area (area_id, area_name) values (308, 'Carpenter');
insert into area (area_id, area_name) values (309, 'Atwood');
insert into area (area_id, area_name) values (310, 'Pepper Wood');
insert into area (area_id, area_name) values (311, 'Coolidge');
insert into area (area_id, area_name) values (312, 'Schmedeman');
insert into area (area_id, area_name) values (313, 'Algoma');
insert into area (area_id, area_name) values (314, '3rd');
insert into area (area_id, area_name) values (315, 'Little Fleur');
insert into area (area_id, area_name) values (316, 'Del Sol');
insert into area (area_id, area_name) values (317, 'Tony');
insert into area (area_id, area_name) values (318, 'Clemons');
insert into area (area_id, area_name) values (319, 'Wayridge');
insert into area (area_id, area_name) values (320, 'Dorton');
insert into area (area_id, area_name) values (321, 'Goodland');
insert into area (area_id, area_name) values (322, 'Michigan');
insert into area (area_id, area_name) values (323, 'Cherokee');
insert into area (area_id, area_name) values (324, 'Sachtjen');
insert into area (area_id, area_name) values (325, 'Bashford');
insert into area (area_id, area_name) values (326, 'Main');
insert into area (area_id, area_name) values (327, 'Delladonna');
insert into area (area_id, area_name) values (328, 'Hanover');
insert into area (area_id, area_name) values (329, 'Holmberg');
insert into area (area_id, area_name) values (330, 'Reinke');
insert into area (area_id, area_name) values (331, 'Kedzie');
insert into area (area_id, area_name) values (332, 'Mendota');
insert into area (area_id, area_name) values (333, 'Golf');
insert into area (area_id, area_name) values (334, 'Arrowood');
insert into area (area_id, area_name) values (335, 'Warrior');
insert into area (area_id, area_name) values (336, 'Weeping Birch');
insert into area (area_id, area_name) values (337, 'Eagan');
insert into area (area_id, area_name) values (338, 'Pawling');
insert into area (area_id, area_name) values (339, 'Linden');
insert into area (area_id, area_name) values (340, 'Northland');
insert into area (area_id, area_name) values (341, 'Iowa');
insert into area (area_id, area_name) values (342, 'Mallory');
insert into area (area_id, area_name) values (343, 'Pine View');
insert into area (area_id, area_name) values (344, 'Gerald');
insert into area (area_id, area_name) values (345, 'Coolidge');
insert into area (area_id, area_name) values (346, 'Crowley');
insert into area (area_id, area_name) values (347, 'Bellgrove');
insert into area (area_id, area_name) values (348, 'Loeprich');
insert into area (area_id, area_name) values (349, 'School');
insert into area (area_id, area_name) values (350, 'Bunker Hill');
insert into area (area_id, area_name) values (351, 'Oriole');
insert into area (area_id, area_name) values (352, 'Hudson');
insert into area (area_id, area_name) values (353, 'Park Meadow');
insert into area (area_id, area_name) values (354, 'Sutherland');
insert into area (area_id, area_name) values (355, 'Superior');
insert into area (area_id, area_name) values (356, 'Green Ridge');
insert into area (area_id, area_name) values (357, 'Fallview');
insert into area (area_id, area_name) values (358, 'Heffernan');
insert into area (area_id, area_name) values (359, 'Stephen');
insert into area (area_id, area_name) values (360, 'Swallow');
insert into area (area_id, area_name) values (361, 'Maryland');
insert into area (area_id, area_name) values (362, 'Main');
insert into area (area_id, area_name) values (363, 'Shopko');
insert into area (area_id, area_name) values (364, 'Eagle Crest');
insert into area (area_id, area_name) values (365, 'Logan');
insert into area (area_id, area_name) values (366, '6th');
insert into area (area_id, area_name) values (367, 'Lakewood');
insert into area (area_id, area_name) values (368, 'Warbler');
insert into area (area_id, area_name) values (369, 'Forster');
insert into area (area_id, area_name) values (370, 'Meadow Valley');
insert into area (area_id, area_name) values (371, 'Blue Bill Park');
insert into area (area_id, area_name) values (372, 'Oak Valley');
insert into area (area_id, area_name) values (373, 'Lukken');
insert into area (area_id, area_name) values (374, 'Ridgeway');
insert into area (area_id, area_name) values (375, 'Mifflin');
insert into area (area_id, area_name) values (376, 'Ryan');
insert into area (area_id, area_name) values (377, 'Shopko');
insert into area (area_id, area_name) values (378, 'Tennyson');
insert into area (area_id, area_name) values (379, 'Ludington');
insert into area (area_id, area_name) values (380, 'Macpherson');
insert into area (area_id, area_name) values (381, 'Nevada');
insert into area (area_id, area_name) values (382, 'Jay');
insert into area (area_id, area_name) values (383, 'Caliangt');
insert into area (area_id, area_name) values (384, 'Jana');
insert into area (area_id, area_name) values (385, 'Buell');
insert into area (area_id, area_name) values (386, 'Eagle Crest');
insert into area (area_id, area_name) values (387, 'Kim');
insert into area (area_id, area_name) values (388, 'Myrtle');
insert into area (area_id, area_name) values (389, 'Hoffman');
insert into area (area_id, area_name) values (390, 'North');
insert into area (area_id, area_name) values (391, 'Colorado');
insert into area (area_id, area_name) values (392, 'Becker');
insert into area (area_id, area_name) values (393, 'Banding');
insert into area (area_id, area_name) values (394, 'Lighthouse Bay');
insert into area (area_id, area_name) values (395, 'Prentice');
insert into area (area_id, area_name) values (396, 'Ludington');
insert into area (area_id, area_name) values (397, 'Kedzie');
insert into area (area_id, area_name) values (398, 'Moulton');
insert into area (area_id, area_name) values (399, 'Anderson');
insert into area (area_id, area_name) values (400, 'Nancy');
insert into area (area_id, area_name) values (401, 'Northfield');
insert into area (area_id, area_name) values (402, 'Scott');
insert into area (area_id, area_name) values (403, 'Graedel');
insert into area (area_id, area_name) values (404, 'Sauthoff');
insert into area (area_id, area_name) values (405, 'Arrowood');
insert into area (area_id, area_name) values (406, 'Leroy');
insert into area (area_id, area_name) values (407, 'Truax');
insert into area (area_id, area_name) values (408, 'Green');
insert into area (area_id, area_name) values (409, 'Golf Course');
insert into area (area_id, area_name) values (410, 'Heffernan');
insert into area (area_id, area_name) values (411, 'Prairie Rose');
insert into area (area_id, area_name) values (412, 'Mallory');
insert into area (area_id, area_name) values (413, 'Westridge');
insert into area (area_id, area_name) values (414, 'Lukken');
insert into area (area_id, area_name) values (415, 'Sauthoff');
insert into area (area_id, area_name) values (416, '3rd');
insert into area (area_id, area_name) values (417, 'Elmside');
insert into area (area_id, area_name) values (418, 'Homewood');
insert into area (area_id, area_name) values (419, 'Dakota');
insert into area (area_id, area_name) values (420, 'Schlimgen');
insert into area (area_id, area_name) values (421, 'Fieldstone');
insert into area (area_id, area_name) values (422, 'Superior');
insert into area (area_id, area_name) values (423, 'Nelson');
insert into area (area_id, area_name) values (424, 'Graedel');
insert into area (area_id, area_name) values (425, 'Rutledge');
insert into area (area_id, area_name) values (426, 'Mosinee');
insert into area (area_id, area_name) values (427, 'Union');
insert into area (area_id, area_name) values (428, 'Nobel');
insert into area (area_id, area_name) values (429, 'Gulseth');
insert into area (area_id, area_name) values (430, 'Mcguire');
insert into area (area_id, area_name) values (431, 'Atwood');
insert into area (area_id, area_name) values (432, 'Pierstorff');
insert into area (area_id, area_name) values (433, 'Cherokee');
insert into area (area_id, area_name) values (434, 'Texas');
insert into area (area_id, area_name) values (435, 'Del Mar');
insert into area (area_id, area_name) values (436, 'Toban');
insert into area (area_id, area_name) values (437, 'Mcguire');
insert into area (area_id, area_name) values (438, 'Vahlen');
insert into area (area_id, area_name) values (439, 'Calypso');
insert into area (area_id, area_name) values (440, 'Havey');
insert into area (area_id, area_name) values (441, 'Hallows');
insert into area (area_id, area_name) values (442, 'Anhalt');
insert into area (area_id, area_name) values (443, 'Morningstar');
insert into area (area_id, area_name) values (444, 'Pond');
insert into area (area_id, area_name) values (445, 'Brentwood');
insert into area (area_id, area_name) values (446, 'Westerfield');
insert into area (area_id, area_name) values (447, 'Autumn Leaf');
insert into area (area_id, area_name) values (448, 'Thackeray');
insert into area (area_id, area_name) values (449, 'Old Shore');
insert into area (area_id, area_name) values (450, 'Dapin');
insert into area (area_id, area_name) values (451, 'Kingsford');
insert into area (area_id, area_name) values (452, 'Sutherland');
insert into area (area_id, area_name) values (453, 'Buell');
insert into area (area_id, area_name) values (454, 'Brown');
insert into area (area_id, area_name) values (455, 'Sunbrook');
insert into area (area_id, area_name) values (456, 'Towne');
insert into area (area_id, area_name) values (457, 'Everett');
insert into area (area_id, area_name) values (458, 'Bluestem');
insert into area (area_id, area_name) values (459, 'School');
insert into area (area_id, area_name) values (460, 'Northland');
insert into area (area_id, area_name) values (461, 'Sachs');
insert into area (area_id, area_name) values (462, 'Shelley');
insert into area (area_id, area_name) values (463, 'David');
insert into area (area_id, area_name) values (464, 'Arrowood');
insert into area (area_id, area_name) values (465, 'Walton');
insert into area (area_id, area_name) values (466, 'Center');
insert into area (area_id, area_name) values (467, 'Dorton');
insert into area (area_id, area_name) values (468, 'Carberry');
insert into area (area_id, area_name) values (469, 'Sage');
insert into area (area_id, area_name) values (470, 'Del Sol');
insert into area (area_id, area_name) values (471, 'Bartillon');
insert into area (area_id, area_name) values (472, 'Sunbrook');
insert into area (area_id, area_name) values (473, 'Lerdahl');
insert into area (area_id, area_name) values (474, 'Victoria');
insert into area (area_id, area_name) values (475, 'Chive');
insert into area (area_id, area_name) values (476, 'Mariners Cove');
insert into area (area_id, area_name) values (477, 'Rockefeller');
insert into area (area_id, area_name) values (478, 'Eliot');
insert into area (area_id, area_name) values (479, 'Rowland');
insert into area (area_id, area_name) values (480, 'Bluejay');
insert into area (area_id, area_name) values (481, 'Delaware');
insert into area (area_id, area_name) values (482, 'Mcbride');
insert into area (area_id, area_name) values (483, 'Prairieview');
insert into area (area_id, area_name) values (484, 'Tony');
insert into area (area_id, area_name) values (485, 'Nova');
insert into area (area_id, area_name) values (486, 'Tennyson');
insert into area (area_id, area_name) values (487, 'Saint Paul');
insert into area (area_id, area_name) values (488, 'Atwood');
insert into area (area_id, area_name) values (489, 'Sauthoff');
insert into area (area_id, area_name) values (490, 'Kings');
insert into area (area_id, area_name) values (491, 'Menomonie');
insert into area (area_id, area_name) values (492, '3rd');
insert into area (area_id, area_name) values (493, 'Schiller');
insert into area (area_id, area_name) values (494, 'Lakewood Gardens');
insert into area (area_id, area_name) values (495, 'Scofield');
insert into area (area_id, area_name) values (496, 'Fallview');
insert into area (area_id, area_name) values (497, 'Hazelcrest');
insert into area (area_id, area_name) values (498, 'Ilene');
insert into area (area_id, area_name) values (499, 'Main');
insert into area (area_id, area_name) values (500, '2nd');
