insert into city (city_id, city_name) values (1, 'Pinillos');
insert into city (city_id, city_name) values (2, 'Guantian');
insert into city (city_id, city_name) values (3, 'Baoshan');
insert into city (city_id, city_name) values (4, 'Fusagasuga');
insert into city (city_id, city_name) values (5, 'Lorino');
insert into city (city_id, city_name) values (6, 'Hodkovice nad Mohelkou');
insert into city (city_id, city_name) values (7, 'Jabłonica Polska');
insert into city (city_id, city_name) values (8, 'Stupari');
insert into city (city_id, city_name) values (9, 'Repušnica');
insert into city (city_id, city_name) values (10, 'Trois-Rivières');
insert into city (city_id, city_name) values (11, 'Casigua El Cubo');
insert into city (city_id, city_name) values (12, 'Lebel-sur-Quévillon');
insert into city (city_id, city_name) values (13, 'Kajatian');
insert into city (city_id, city_name) values (14, 'Xiaolou');
insert into city (city_id, city_name) values (15, 'Deskáti');
insert into city (city_id, city_name) values (16, 'Kuala Terengganu');
insert into city (city_id, city_name) values (17, 'Naawan');
insert into city (city_id, city_name) values (18, 'Divichibazar');
insert into city (city_id, city_name) values (19, 'Créteil');
insert into city (city_id, city_name) values (20, 'Tianqian');
insert into city (city_id, city_name) values (21, 'Fteliá');
insert into city (city_id, city_name) values (22, 'Heshui');
insert into city (city_id, city_name) values (23, 'Tomepampa');
insert into city (city_id, city_name) values (24, 'Shikhany');
insert into city (city_id, city_name) values (25, 'Valenciennes');
insert into city (city_id, city_name) values (26, 'Heemskerk');
insert into city (city_id, city_name) values (27, 'Zeqin');
insert into city (city_id, city_name) values (28, 'Čeladná');
insert into city (city_id, city_name) values (29, 'Saint Ann’s Bay');
insert into city (city_id, city_name) values (30, 'Tarko-Sale');
insert into city (city_id, city_name) values (31, 'Qinggang');
insert into city (city_id, city_name) values (32, 'Krásná Hora nad Vltavou');
insert into city (city_id, city_name) values (33, 'Yono');
insert into city (city_id, city_name) values (34, 'Huangjindong');
insert into city (city_id, city_name) values (35, 'Madrid');
insert into city (city_id, city_name) values (36, 'Sumber');
insert into city (city_id, city_name) values (37, 'Saint-Jean-de-Védas');
insert into city (city_id, city_name) values (38, 'Narathiwat');
insert into city (city_id, city_name) values (39, 'Nakajah');
insert into city (city_id, city_name) values (40, 'Tōno');
insert into city (city_id, city_name) values (41, 'Novohrad-Volyns’kyy');
insert into city (city_id, city_name) values (42, 'Qixingtai');
insert into city (city_id, city_name) values (43, 'Hesi');
insert into city (city_id, city_name) values (44, 'Néos Mylótopos');
insert into city (city_id, city_name) values (45, 'Zhoupi');
insert into city (city_id, city_name) values (46, 'Mach');
insert into city (city_id, city_name) values (47, 'Songjiang');
insert into city (city_id, city_name) values (48, 'Mỹ Tho');
insert into city (city_id, city_name) values (49, 'Dashi');
insert into city (city_id, city_name) values (50, 'Río Segundo');
insert into city (city_id, city_name) values (51, 'Hasaki');
insert into city (city_id, city_name) values (52, 'Kolno');
insert into city (city_id, city_name) values (53, 'Domaniewice');
insert into city (city_id, city_name) values (54, 'Kungshamn');
insert into city (city_id, city_name) values (55, 'Magdaleno Aguilar');
insert into city (city_id, city_name) values (56, 'Kiambu');
insert into city (city_id, city_name) values (57, 'Kyzylorda');
insert into city (city_id, city_name) values (58, 'Uglyanets');
insert into city (city_id, city_name) values (59, 'Kuttu');
insert into city (city_id, city_name) values (60, 'Nanjiao');
insert into city (city_id, city_name) values (61, 'Yoshkar-Ola');
insert into city (city_id, city_name) values (62, 'Logung');
insert into city (city_id, city_name) values (63, 'Haradzyeya');
insert into city (city_id, city_name) values (64, 'Aloleng');
insert into city (city_id, city_name) values (65, 'Baltimore');
insert into city (city_id, city_name) values (66, 'Shilong');
insert into city (city_id, city_name) values (67, 'Sukamulya');
insert into city (city_id, city_name) values (68, 'Xinmin');
insert into city (city_id, city_name) values (69, 'Boston');
insert into city (city_id, city_name) values (70, 'Bungoma');
insert into city (city_id, city_name) values (71, 'Nakambala');
insert into city (city_id, city_name) values (72, 'Dikou');
insert into city (city_id, city_name) values (73, 'Xianxiang');
insert into city (city_id, city_name) values (74, 'Zhuhe');
insert into city (city_id, city_name) values (75, 'Lambton Shores');
insert into city (city_id, city_name) values (76, 'Zmeyskaya');
insert into city (city_id, city_name) values (77, 'Krajanpagowan');
insert into city (city_id, city_name) values (78, 'Liuzhou');
insert into city (city_id, city_name) values (79, 'Limoges');
insert into city (city_id, city_name) values (80, 'Gampaha');
insert into city (city_id, city_name) values (81, 'Zhujiapu');
insert into city (city_id, city_name) values (82, 'Garupá');
insert into city (city_id, city_name) values (83, 'Konobeyevo');
insert into city (city_id, city_name) values (84, 'Shigony');
insert into city (city_id, city_name) values (85, 'San Nicolas');
insert into city (city_id, city_name) values (86, 'Citarik');
insert into city (city_id, city_name) values (87, 'Gaoqiu');
insert into city (city_id, city_name) values (88, 'Cova da Iria');
insert into city (city_id, city_name) values (89, 'Fryazino');
insert into city (city_id, city_name) values (90, 'Beiyang');
insert into city (city_id, city_name) values (91, 'Abū Tīj');
insert into city (city_id, city_name) values (92, 'Tianyu');
insert into city (city_id, city_name) values (93, 'Maldonado');
insert into city (city_id, city_name) values (94, 'Kirovohrad');
insert into city (city_id, city_name) values (95, 'Cidikit Girang');
insert into city (city_id, city_name) values (96, 'Sankeyushu');
insert into city (city_id, city_name) values (97, 'Bo Kluea');
insert into city (city_id, city_name) values (98, 'Hepo');
insert into city (city_id, city_name) values (99, 'Cuyotenango');
insert into city (city_id, city_name) values (100, 'Tongqing');
insert into city (city_id, city_name) values (101, 'Tochigi');
insert into city (city_id, city_name) values (102, 'Włocławek');
insert into city (city_id, city_name) values (103, 'Chowṉêy');
insert into city (city_id, city_name) values (104, 'Chongkan');
insert into city (city_id, city_name) values (105, 'Moravský Krumlov');
insert into city (city_id, city_name) values (106, 'Jakhaly');
insert into city (city_id, city_name) values (107, 'Busia');
insert into city (city_id, city_name) values (108, 'Sarukhan');
insert into city (city_id, city_name) values (109, 'Kulunda');
insert into city (city_id, city_name) values (110, 'Jieyang');
insert into city (city_id, city_name) values (111, 'Al Muharraq');
insert into city (city_id, city_name) values (112, 'Miami');
insert into city (city_id, city_name) values (113, 'Papilawe');
insert into city (city_id, city_name) values (114, 'Waigete');
insert into city (city_id, city_name) values (115, 'Adh Dhayd');
insert into city (city_id, city_name) values (116, 'Pirava');
insert into city (city_id, city_name) values (117, 'Syzran’');
insert into city (city_id, city_name) values (118, 'Edinburgh');
insert into city (city_id, city_name) values (119, 'Chengkou');
insert into city (city_id, city_name) values (120, 'Dobri Dol');
insert into city (city_id, city_name) values (121, 'Drenova');
insert into city (city_id, city_name) values (122, 'Kushnytsya');
insert into city (city_id, city_name) values (123, 'Buštěhrad');
insert into city (city_id, city_name) values (124, 'Petro-Slavyanka');
insert into city (city_id, city_name) values (125, 'Tocoa');
insert into city (city_id, city_name) values (126, 'Loures');
insert into city (city_id, city_name) values (127, 'Mpulungu');
insert into city (city_id, city_name) values (128, 'Purda');
insert into city (city_id, city_name) values (129, 'Curridabat');
insert into city (city_id, city_name) values (130, 'Kokar');
insert into city (city_id, city_name) values (131, 'Aygeshat');
insert into city (city_id, city_name) values (132, 'Tiassalé');
insert into city (city_id, city_name) values (133, 'Neob');
insert into city (city_id, city_name) values (134, 'Dampol');
insert into city (city_id, city_name) values (135, 'Baranovichi');
insert into city (city_id, city_name) values (136, 'Kočevje');
insert into city (city_id, city_name) values (137, 'Maoya');
insert into city (city_id, city_name) values (138, 'Karangsari');
insert into city (city_id, city_name) values (139, 'Louguan');
insert into city (city_id, city_name) values (140, 'Goragorskiy');
insert into city (city_id, city_name) values (141, 'Kawasaki');
insert into city (city_id, city_name) values (142, 'Qian’an');
insert into city (city_id, city_name) values (143, 'Boende');
insert into city (city_id, city_name) values (144, 'Krásná Hora nad Vltavou');
insert into city (city_id, city_name) values (145, 'Cuilco');
insert into city (city_id, city_name) values (146, 'Kostanay');
insert into city (city_id, city_name) values (147, 'Talacogon');
insert into city (city_id, city_name) values (148, 'Bagusan');
insert into city (city_id, city_name) values (149, 'Misungwi');
insert into city (city_id, city_name) values (150, 'Jiḩānah');
insert into city (city_id, city_name) values (151, 'Buđanovci');
insert into city (city_id, city_name) values (152, 'Kalininskiy');
insert into city (city_id, city_name) values (153, 'Hengxizhen');
insert into city (city_id, city_name) values (154, 'Evansville');
insert into city (city_id, city_name) values (155, 'Bystrytsya');
insert into city (city_id, city_name) values (156, 'La Jagua de Ibirico');
insert into city (city_id, city_name) values (157, 'Natal');
insert into city (city_id, city_name) values (158, 'Jönköping');
insert into city (city_id, city_name) values (159, 'White City');
insert into city (city_id, city_name) values (160, 'Vygonichi');
insert into city (city_id, city_name) values (161, 'Dong’an');
insert into city (city_id, city_name) values (162, 'Jiagao');
insert into city (city_id, city_name) values (163, 'Krasnofarfornyy');
insert into city (city_id, city_name) values (164, 'Junín');
insert into city (city_id, city_name) values (165, 'Vera Cruz');
insert into city (city_id, city_name) values (166, 'Wolongquan');
insert into city (city_id, city_name) values (167, 'Olocuilta');
insert into city (city_id, city_name) values (168, 'Laspezia');
insert into city (city_id, city_name) values (169, 'Chingas');
insert into city (city_id, city_name) values (170, 'Archis');
insert into city (city_id, city_name) values (171, 'Pul-e Khumrī');
insert into city (city_id, city_name) values (172, 'Szeged');
insert into city (city_id, city_name) values (173, 'Longmen');
insert into city (city_id, city_name) values (174, 'Roi Et');
insert into city (city_id, city_name) values (175, 'Sandefjord');
insert into city (city_id, city_name) values (176, 'Alderetes');
insert into city (city_id, city_name) values (177, 'Nowogard');
insert into city (city_id, city_name) values (178, 'Saribudolok');
insert into city (city_id, city_name) values (179, 'Chornyanka');
insert into city (city_id, city_name) values (180, 'Panguna');
insert into city (city_id, city_name) values (181, 'Qarah Ẕīā’ od Dīn');
insert into city (city_id, city_name) values (182, 'Lincha');
insert into city (city_id, city_name) values (183, 'Falënki');
insert into city (city_id, city_name) values (184, 'Porangatu');
insert into city (city_id, city_name) values (185, 'Svetlyy Yar');
insert into city (city_id, city_name) values (186, 'Nîmes');
insert into city (city_id, city_name) values (187, 'Delaware');
insert into city (city_id, city_name) values (188, 'Siumate');
insert into city (city_id, city_name) values (189, 'Ishigaki');
insert into city (city_id, city_name) values (190, 'Mougins');
insert into city (city_id, city_name) values (191, 'Przemęt');
insert into city (city_id, city_name) values (192, 'Zhangxiong');
insert into city (city_id, city_name) values (193, 'Adani');
insert into city (city_id, city_name) values (194, 'Bolong');
insert into city (city_id, city_name) values (195, 'Hantsavichy');
insert into city (city_id, city_name) values (196, 'Sibulan');
insert into city (city_id, city_name) values (197, 'Shuinan');
insert into city (city_id, city_name) values (198, 'Yuanbao');
insert into city (city_id, city_name) values (199, 'Rzhev');
insert into city (city_id, city_name) values (200, 'Thymianá');
insert into city (city_id, city_name) values (201, 'Kaligutan');
insert into city (city_id, city_name) values (202, 'Kai');
insert into city (city_id, city_name) values (203, 'Guta');
insert into city (city_id, city_name) values (204, 'Skołyszyn');
insert into city (city_id, city_name) values (205, 'Tosu');
insert into city (city_id, city_name) values (206, 'El Aguacate');
insert into city (city_id, city_name) values (207, 'Jiangdianzi');
insert into city (city_id, city_name) values (208, 'Aigínio');
insert into city (city_id, city_name) values (209, 'Gangdong');
insert into city (city_id, city_name) values (210, 'Cajamar');
insert into city (city_id, city_name) values (211, 'Shar’ya');
insert into city (city_id, city_name) values (212, 'Bitaogan');
insert into city (city_id, city_name) values (213, 'Santa Bárbara d''Oeste');
insert into city (city_id, city_name) values (214, 'Gnieżdżewo');
insert into city (city_id, city_name) values (215, 'Huipinggeng');
insert into city (city_id, city_name) values (216, 'Naqadeh');
insert into city (city_id, city_name) values (217, 'Merklín');
insert into city (city_id, city_name) values (218, 'Karatsu');
insert into city (city_id, city_name) values (219, 'Shumikha');
insert into city (city_id, city_name) values (220, 'Rego de Água');
insert into city (city_id, city_name) values (221, 'Yezhu');
insert into city (city_id, city_name) values (222, 'Gravataí');
insert into city (city_id, city_name) values (223, 'Lopatinskiy');
insert into city (city_id, city_name) values (224, 'Wleń');
insert into city (city_id, city_name) values (225, 'Šid');
insert into city (city_id, city_name) values (226, 'Staryy Oskol');
insert into city (city_id, city_name) values (227, 'Antou');
insert into city (city_id, city_name) values (228, 'Turenki');
insert into city (city_id, city_name) values (229, 'Dukou');
insert into city (city_id, city_name) values (230, 'Ibirama');
insert into city (city_id, city_name) values (231, 'Valence');
insert into city (city_id, city_name) values (232, 'Vänersborg');
insert into city (city_id, city_name) values (233, 'Växjö');
insert into city (city_id, city_name) values (234, 'Haitou');
insert into city (city_id, city_name) values (235, 'Bắc Kạn');
insert into city (city_id, city_name) values (236, 'Curvelo');
insert into city (city_id, city_name) values (237, 'Metahāra');
insert into city (city_id, city_name) values (238, 'Terbangan');
insert into city (city_id, city_name) values (239, 'Kumagunnam');
insert into city (city_id, city_name) values (240, 'Puksoozero');
insert into city (city_id, city_name) values (241, 'Huanoquite');
insert into city (city_id, city_name) values (242, 'Huainan');
insert into city (city_id, city_name) values (243, 'Gravatá');
insert into city (city_id, city_name) values (244, 'Shuangxi');
insert into city (city_id, city_name) values (245, 'Panyindangan');
insert into city (city_id, city_name) values (246, 'Dębno');
insert into city (city_id, city_name) values (247, 'Tiraspol');
insert into city (city_id, city_name) values (248, 'Novi Bečej');
insert into city (city_id, city_name) values (249, 'Kislyakovskaya');
insert into city (city_id, city_name) values (250, 'Toyooka');
insert into city (city_id, city_name) values (251, 'Grahamstown');
insert into city (city_id, city_name) values (252, 'Žrnovnica');
insert into city (city_id, city_name) values (253, 'Ueno');
insert into city (city_id, city_name) values (254, 'Pengshi');
insert into city (city_id, city_name) values (255, 'Kristinehamn');
insert into city (city_id, city_name) values (256, 'Chipoka');
insert into city (city_id, city_name) values (257, 'Dayou');
insert into city (city_id, city_name) values (258, 'Fermelã');
insert into city (city_id, city_name) values (259, 'Matola');
insert into city (city_id, city_name) values (260, 'Bembèrèkè');
insert into city (city_id, city_name) values (261, 'Hulan');
insert into city (city_id, city_name) values (262, 'Sibanicú');
insert into city (city_id, city_name) values (263, 'Medeiros Neto');
insert into city (city_id, city_name) values (264, 'Dhībīn');
insert into city (city_id, city_name) values (265, 'Olenyok');
insert into city (city_id, city_name) values (266, 'Saxin');
insert into city (city_id, city_name) values (267, 'Kroya');
insert into city (city_id, city_name) values (268, 'Houston');
insert into city (city_id, city_name) values (269, 'São Sebastião do Caí');
insert into city (city_id, city_name) values (270, 'Gorno Orizari');
insert into city (city_id, city_name) values (271, 'Cipari');
insert into city (city_id, city_name) values (272, 'Xiaotao');
insert into city (city_id, city_name) values (273, 'Kuloy');
insert into city (city_id, city_name) values (274, 'Rybnoye');
insert into city (city_id, city_name) values (275, 'Jinjia');
insert into city (city_id, city_name) values (276, 'Jieting');
insert into city (city_id, city_name) values (277, 'Aquia');
insert into city (city_id, city_name) values (278, 'Itambé');
insert into city (city_id, city_name) values (279, 'Kaélé');
insert into city (city_id, city_name) values (280, 'Firá');
insert into city (city_id, city_name) values (281, 'San Antonio Ilotenango');
insert into city (city_id, city_name) values (282, 'Narsingdi');
insert into city (city_id, city_name) values (283, 'Zhushan');
insert into city (city_id, city_name) values (284, 'Tabaga');
insert into city (city_id, city_name) values (285, 'Niimi');
insert into city (city_id, city_name) values (286, 'Yinjiang');
insert into city (city_id, city_name) values (287, 'Pangansalan');
insert into city (city_id, city_name) values (288, 'Leuwipicung');
insert into city (city_id, city_name) values (289, 'Cimonyong');
insert into city (city_id, city_name) values (290, 'Opuzen');
insert into city (city_id, city_name) values (291, 'Tanarara');
insert into city (city_id, city_name) values (292, 'Leuwidamar');
insert into city (city_id, city_name) values (293, 'Osekovo');
insert into city (city_id, city_name) values (294, 'Novomykolayivka');
insert into city (city_id, city_name) values (295, 'Aimadamodo');
insert into city (city_id, city_name) values (296, 'Wenjiao');
insert into city (city_id, city_name) values (297, 'Gaolong');
insert into city (city_id, city_name) values (298, 'Guacara');
insert into city (city_id, city_name) values (299, 'Likupang');
insert into city (city_id, city_name) values (300, 'Jiangxigou');
insert into city (city_id, city_name) values (301, 'São Vicente');
insert into city (city_id, city_name) values (302, 'Xinyang');
insert into city (city_id, city_name) values (303, 'Criação Velha');
insert into city (city_id, city_name) values (304, 'Lagdo');
insert into city (city_id, city_name) values (305, 'Toulon');
insert into city (city_id, city_name) values (306, 'Shache');
insert into city (city_id, city_name) values (307, 'Cogtong');
insert into city (city_id, city_name) values (308, 'Samparna');
insert into city (city_id, city_name) values (309, 'João Monlevade');
insert into city (city_id, city_name) values (310, 'Buhe');
insert into city (city_id, city_name) values (311, 'Pico da Pedra');
insert into city (city_id, city_name) values (312, 'Qingyang');
insert into city (city_id, city_name) values (313, 'Yujiao');
insert into city (city_id, city_name) values (314, 'Misasi');
insert into city (city_id, city_name) values (315, 'Yanhong');
insert into city (city_id, city_name) values (316, 'Senglea');
insert into city (city_id, city_name) values (317, 'Sasovo');
insert into city (city_id, city_name) values (318, 'Trinity Ville');
insert into city (city_id, city_name) values (319, 'Nardaran');
insert into city (city_id, city_name) values (320, 'Chengjiao Chengguanzhen');
insert into city (city_id, city_name) values (321, 'Tromsø');
insert into city (city_id, city_name) values (322, 'Galaz');
insert into city (city_id, city_name) values (323, 'Saseel');
insert into city (city_id, city_name) values (324, 'Shuangshipu');
insert into city (city_id, city_name) values (325, 'Gunziying');
insert into city (city_id, city_name) values (326, 'Almaguer');
insert into city (city_id, city_name) values (327, 'Faruka');
insert into city (city_id, city_name) values (328, 'Awar-awar');
insert into city (city_id, city_name) values (329, 'Kirovgrad');
insert into city (city_id, city_name) values (330, 'Wolanów');
insert into city (city_id, city_name) values (331, 'Kamalasai');
insert into city (city_id, city_name) values (332, 'Ciela Lebak');
insert into city (city_id, city_name) values (333, 'San Vicente Pacaya');
insert into city (city_id, city_name) values (334, 'Ulaan-Uul');
insert into city (city_id, city_name) values (335, 'Pedome');
insert into city (city_id, city_name) values (336, 'Farsta');
insert into city (city_id, city_name) values (337, 'Quintinha');
insert into city (city_id, city_name) values (338, 'Kihangara');
insert into city (city_id, city_name) values (339, 'Naju');
insert into city (city_id, city_name) values (340, 'Cidadap');
insert into city (city_id, city_name) values (341, 'Jiangdianzi');
insert into city (city_id, city_name) values (342, 'Liverpool');
insert into city (city_id, city_name) values (343, 'Tambov');
insert into city (city_id, city_name) values (344, 'Mirovice');
insert into city (city_id, city_name) values (345, 'Navoiy');
insert into city (city_id, city_name) values (346, 'Sosnówka');
insert into city (city_id, city_name) values (347, 'Fengtai Chengguanzhen');
insert into city (city_id, city_name) values (348, 'Madrid');
insert into city (city_id, city_name) values (349, 'Fengniancun');
insert into city (city_id, city_name) values (350, 'Stockholm');
insert into city (city_id, city_name) values (351, 'Vinica');
insert into city (city_id, city_name) values (352, 'Huskvarna');
insert into city (city_id, city_name) values (353, 'Banjar Kampungbugis');
insert into city (city_id, city_name) values (354, 'Siqian');
insert into city (city_id, city_name) values (355, 'Dassun');
insert into city (city_id, city_name) values (356, 'Thị Trấn Triệu Sơn');
insert into city (city_id, city_name) values (357, 'Yanglang');
insert into city (city_id, city_name) values (358, 'Reims');
insert into city (city_id, city_name) values (359, 'Jiaozuo');
insert into city (city_id, city_name) values (360, 'Baizhang');
insert into city (city_id, city_name) values (361, 'Ergong');
insert into city (city_id, city_name) values (362, 'Qobu');
insert into city (city_id, city_name) values (363, 'Uusikaupunki');
insert into city (city_id, city_name) values (364, 'Gereykhanovskoye');
insert into city (city_id, city_name) values (365, 'Toyokawa');
insert into city (city_id, city_name) values (366, 'Yartsevo');
insert into city (city_id, city_name) values (367, 'Rožmitál pod Třemšínem');
insert into city (city_id, city_name) values (368, 'Lüxiang');
insert into city (city_id, city_name) values (369, 'Dvorichna');
insert into city (city_id, city_name) values (370, 'Dayeuhluhur');
insert into city (city_id, city_name) values (371, 'Lewodoli');
insert into city (city_id, city_name) values (372, 'Oyabe');
insert into city (city_id, city_name) values (373, 'Watubura');
insert into city (city_id, city_name) values (374, 'Xieji');
insert into city (city_id, city_name) values (375, 'Drahovo');
insert into city (city_id, city_name) values (376, 'Padangtikar');
insert into city (city_id, city_name) values (377, 'Coro');
insert into city (city_id, city_name) values (378, 'Le Mans');
insert into city (city_id, city_name) values (379, 'Nong Yai');
insert into city (city_id, city_name) values (380, 'Njivice');
insert into city (city_id, city_name) values (381, 'Qianshan');
insert into city (city_id, city_name) values (382, 'Andir');
insert into city (city_id, city_name) values (383, 'El Carril');
insert into city (city_id, city_name) values (384, 'Lilin Satu');
insert into city (city_id, city_name) values (385, 'Campbellton');
insert into city (city_id, city_name) values (386, 'Gedaliang');
insert into city (city_id, city_name) values (387, 'Deqing');
insert into city (city_id, city_name) values (388, 'Aurora');
insert into city (city_id, city_name) values (389, 'Karagandy');
insert into city (city_id, city_name) values (390, 'Municipio de Copacabana');
insert into city (city_id, city_name) values (391, 'Ligang');
insert into city (city_id, city_name) values (392, 'Oslo');
insert into city (city_id, city_name) values (393, 'Berëza');
insert into city (city_id, city_name) values (394, 'Perpignan');
insert into city (city_id, city_name) values (395, 'Guohe');
insert into city (city_id, city_name) values (396, 'Yangong');
insert into city (city_id, city_name) values (397, 'Bastos');
insert into city (city_id, city_name) values (398, 'Casal');
insert into city (city_id, city_name) values (399, 'Lugouqiao');
insert into city (city_id, city_name) values (400, 'Azul');
insert into city (city_id, city_name) values (401, 'Ban Bueng');
insert into city (city_id, city_name) values (402, 'Jiang’an');
insert into city (city_id, city_name) values (403, 'Sawahan');
insert into city (city_id, city_name) values (404, 'Fermelã');
insert into city (city_id, city_name) values (405, 'Hongling');
insert into city (city_id, city_name) values (406, 'Klenica');
insert into city (city_id, city_name) values (407, 'Pingle');
insert into city (city_id, city_name) values (408, 'Portland');
insert into city (city_id, city_name) values (409, 'Hetou');
insert into city (city_id, city_name) values (410, 'Elliot');
insert into city (city_id, city_name) values (411, 'Taiping');
insert into city (city_id, city_name) values (412, 'Heba');
insert into city (city_id, city_name) values (413, 'Sudzha');
insert into city (city_id, city_name) values (414, 'Győr');
insert into city (city_id, city_name) values (415, 'Sibulan');
insert into city (city_id, city_name) values (416, 'Xinhua');
insert into city (city_id, city_name) values (417, 'Kramarzówka');
insert into city (city_id, city_name) values (418, 'Himaya');
insert into city (city_id, city_name) values (419, 'Belyy Gorodok');
insert into city (city_id, city_name) values (420, 'Gort');
insert into city (city_id, city_name) values (421, 'Cibunar');
insert into city (city_id, city_name) values (422, 'Maogou');
insert into city (city_id, city_name) values (423, 'São Mateus do Sul');
insert into city (city_id, city_name) values (424, 'San Martin');
insert into city (city_id, city_name) values (425, 'Makiv');
insert into city (city_id, city_name) values (426, 'Licun');
insert into city (city_id, city_name) values (427, 'Al Ḩāḑir');
insert into city (city_id, city_name) values (428, 'Mabua');
insert into city (city_id, city_name) values (429, 'Preobrazheniye');
insert into city (city_id, city_name) values (430, 'Gunjur Kuta');
insert into city (city_id, city_name) values (431, 'Al Finţās');
insert into city (city_id, city_name) values (432, 'Bouaflé');
insert into city (city_id, city_name) values (433, 'Moriguchi');
insert into city (city_id, city_name) values (434, 'Māymay');
insert into city (city_id, city_name) values (435, 'Krajan');
insert into city (city_id, city_name) values (436, 'Daigo');
insert into city (city_id, city_name) values (437, 'Yangmaogong');
insert into city (city_id, city_name) values (438, 'Sarvaš');
insert into city (city_id, city_name) values (439, 'Rozhniv');
insert into city (city_id, city_name) values (440, 'Babirik');
insert into city (city_id, city_name) values (441, 'Barberton');
insert into city (city_id, city_name) values (442, 'Kecskemét');
insert into city (city_id, city_name) values (443, 'Cikendi');
insert into city (city_id, city_name) values (444, 'Tyresö');
insert into city (city_id, city_name) values (445, 'Korolëv Stan');
insert into city (city_id, city_name) values (446, 'Osek nad Bečvou');
insert into city (city_id, city_name) values (447, 'Sevilla');
insert into city (city_id, city_name) values (448, 'Jaworzyna Śląska');
insert into city (city_id, city_name) values (449, 'Lingquan');
insert into city (city_id, city_name) values (450, 'Khonj');
insert into city (city_id, city_name) values (451, 'Fier');
insert into city (city_id, city_name) values (452, 'Czarnowąsy');
insert into city (city_id, city_name) values (453, 'Stocksund');
insert into city (city_id, city_name) values (454, 'Mafinga');
insert into city (city_id, city_name) values (455, 'Saint Petersburg');
insert into city (city_id, city_name) values (456, 'Sonzacate');
insert into city (city_id, city_name) values (457, 'Muzhijie');
insert into city (city_id, city_name) values (458, 'Geldrop');
insert into city (city_id, city_name) values (459, 'Bozoum');
insert into city (city_id, city_name) values (460, 'Guayaquil');
insert into city (city_id, city_name) values (461, 'Sanming');
insert into city (city_id, city_name) values (462, 'Pinghu');
insert into city (city_id, city_name) values (463, 'Lela');
insert into city (city_id, city_name) values (464, 'Deder');
insert into city (city_id, city_name) values (465, 'Goodlands');
insert into city (city_id, city_name) values (466, 'E’zhou');
insert into city (city_id, city_name) values (467, 'Uyen Hung');
insert into city (city_id, city_name) values (468, 'Vallauris');
insert into city (city_id, city_name) values (469, 'Lanos');
insert into city (city_id, city_name) values (470, 'Vila Viçosa');
insert into city (city_id, city_name) values (471, 'Yonggu');
insert into city (city_id, city_name) values (472, 'Gelgaudiškis');
insert into city (city_id, city_name) values (473, 'Cocabamba');
insert into city (city_id, city_name) values (474, 'La Palma');
insert into city (city_id, city_name) values (475, 'Ngulakan');
insert into city (city_id, city_name) values (476, 'Haoba');
insert into city (city_id, city_name) values (477, 'Didi Lilo');
insert into city (city_id, city_name) values (478, 'Balīlā');
insert into city (city_id, city_name) values (479, 'Mosteiro');
insert into city (city_id, city_name) values (480, 'Akbarābād');
insert into city (city_id, city_name) values (481, 'Aozou');
insert into city (city_id, city_name) values (482, 'Viesīte');
insert into city (city_id, city_name) values (483, 'Dimona');
insert into city (city_id, city_name) values (484, 'Dasha');
insert into city (city_id, city_name) values (485, 'Krajan Langenharjo');
insert into city (city_id, city_name) values (486, 'Cliza');
insert into city (city_id, city_name) values (487, 'Osiedle-Nowiny');
insert into city (city_id, city_name) values (488, 'Dordrecht');
insert into city (city_id, city_name) values (489, 'Oliveira');
insert into city (city_id, city_name) values (490, 'Dongfanghong');
insert into city (city_id, city_name) values (491, 'Namangan Shahri');
insert into city (city_id, city_name) values (492, 'San Nicolás de los Arroyos');
insert into city (city_id, city_name) values (493, 'Saint-Louis');
insert into city (city_id, city_name) values (494, 'Žagarė');
insert into city (city_id, city_name) values (495, 'Jiasi');
insert into city (city_id, city_name) values (496, 'Esquipulas');
insert into city (city_id, city_name) values (497, 'Arhust');
insert into city (city_id, city_name) values (498, 'Pulau Pinang');
insert into city (city_id, city_name) values (499, 'Quanyang');
insert into city (city_id, city_name) values (500, 'Sar Chakān');
